### PR TITLE
Update 03_challenges_future.md

### PR DESCRIPTION
**Pull request by selina-aragon**
A link to "this space" would be useful in "Anyone reading this is welcome to join us: watch this space for further updates!" (37).

This post is missing a conclusion. It would be good to see something that draws from the three blog posts.

### CODE REVIEW

**Comment by tobyhodges** [comment]
I can replace "this space" with actual information about what's happening with those community calls. Should have time later today to do so.

**Comment by tobyhodges** [comment]
BTW thank you for your help with this, @selina-aragon

**Comment by selina-aragon** [comment]
No problem! Let me know when it's ready. I can schedule these three blog posts for next week if you're happy with them.

**Comment by tobyhodges** [comment]
Ok, I've added my part. I guess we can drop the Iterating section at this point?

**Pull request merged**
