### PR TITLE
Update 01_intro.md

### PR DESCRIPTION
**Pull request by selina-aragon**
Hi Anna,

I've made some changes here after all as they are minor edits. Please let me know if you're happy with them. I can publish this post next week (Monday, for example) and publish the other two on Tuesday, then Wednesday. 

Selina.

### CODE REVIEW

**Comment by tobyhodges** [comment]
Thanks for the changes, Selina. I think that this post could use a final sentence setting the scene for what's coming next. Something like, "Check back here tomorrow for the next post, to find out more about what happened when we met..."

**Comment by selina-aragon** [comment]
I agree. Maybe something like: "Check back here tomorrow for the next post on how to successfully build and develop a community"? And once the second post is published, we can add a link.

**Comment by tobyhodges** [comment]
Good suggestion. I've added it now.

This looks good to me (LGTM) now. I'd like to wait and let @annakrystalli take a look through and merge these PRs.

**Comment by annakrystalli** [comment]
Thanks @selina-aragon & @tobyhodges!

I'm a bit tied up today and tomorrow but will have a good look through over the weekend and do a final edit also (there are a couple of gaps that need to be filled). But having monday as a deadline is perfect. Excited for it to be published next week! 🎉✨

**Review by annakrystalli — APPROVED** [review]

**Comment by selina-aragon** [comment]
Hi @annakrystalli @tobyhodges 
Can you let me know when you're happy for this to be published? 

Thanks!
Selina.

**Comment by annakrystalli** [comment]
Hi Selina,

I incorporated all your changes, many thanks. But I have been bogged down working all weekend 😞and not been able to include the edits I wanted to 02 and 03.  I'm just a bit overwhelmed atm but will have some free time from thu when I'll be on annual leave. @tobyhodges what do you think? Should we just go for it? Otherwise I could make the changes if we postponed by a few days. Sorry about all this. I don't want to mess the SSI blog schedule up.

**Comment by selina-aragon** [comment]
Hi Anna,

No worries. Let's postpone a few days so you can look at it without any pressure or rush :) 

Let me know!

**Comment by tobyhodges** [comment]
I think that sections 1 & 2 are ready to go - it's only really the "Iterating" section of part 3 that definitely needs work/removing.

@annakrystalli if you're happy for me to straight-up remove that section, or to add a short sentence or two - about the importance of constantly reviewing what we're doing, learning from our experience, and incorporating these lessons before the next time (this is what I think of when we talk about iterating) - I'd be happy to do that. 

It sounds like you've got a lot on your plate at the moment and, in my opinion, working on side projects is not necessarily what annual leave should be for! Please don't feel obligated to work on this, or any other voluntary project, if some time to rest and relax is what you think you really need. You do amazing work and I'd hate to see that get overwhelming for you. Take care of yourself first, and let us carry some of the weight for you :)

**Comment by annakrystalli** [comment]
@tobyhodges OK toby! If you're happy, I'm happy. So yeah, if you can sort out 03 then I'm happy for them to be published (cc @selina-aragon). 

Thanks for your patience!

**Comment by selina-aragon** [comment]
Hello,

I've published the first one: https://software.ac.uk/blog/2018-05-09-building-communities-support-research-software-engineering-blog-series 
The tweet will go out at 10am :) 

Thanks both,
Selina.

**Comment by tobyhodges** [comment]
Great, thank you Selina!

I’m @tbyhdgs on Twitter :)

**Pull request merged**
